<MyLayout>
	BoxLayout:
		orientation: "vertical"
		size: root.width, root.height
		
		TextInput:
			text: "Enter Text, Link or Path to make the code"
			id: name_input
			multiline: False
			size_hint: (1, .3)
			
		Label:
			id: name_label
			markup: True
			text: "Display QR"
			font_size: 20

		Button:
			size_hint: (1, .3)
			font_size: 50
			text: "Make QR"
			on_press: root.press()
